package net.strukteon.myrpc.utils;

import net.strukteon.myrpc.control.*;

public class TempInterfaceState
{
    private static boolean bt_add_profile;
    private static boolean bt_remove_profile;
    private static boolean bt_timer_settings;
    private static boolean bt_stop_presence;
    private static boolean bt_update_presence;
    private static boolean bt_view_preview_pg1;
    private static boolean bt_add_image;
    private static boolean bt_remove_image;
    private static boolean bt_remove_all_images;
    private static boolean bt_view_preview_pg2;
    private static boolean bt_add_application;
    private static boolean bt_remove_application;
    private static boolean bt_export_to_jar;
    private static boolean cb_profiles;
    private static boolean cb_large_image;
    private static boolean cb_small_image;
    private static boolean ch_show_timer;
    private static boolean ch_large_img_enabled;
    private static boolean ch_small_img_enabled;
    private static boolean lb_profile;
    private static boolean lb_details;
    private static boolean lb_state;
    private static boolean lb_group;
    private static boolean lb_group_cur;
    private static boolean lb_group_max;
    private static boolean lb_app_id;
    private static boolean lb_large_img;
    private static boolean lb_small_img;
    private static boolean lb_view_preview_pg1;
    private static boolean lb_view_preview_pg2;
    private static boolean tf_state;
    private static boolean tf_details;
    private static boolean tf_group_cur;
    private static boolean tf_group_max;
    private static boolean cb_application;
    private static boolean tf_app_id;
    private static boolean tf_large_image;
    private static boolean tf_small_image;
    
    public static void store(final Interface interf) {
        TempInterfaceState.bt_add_profile = interf.bt_add_profile.isDisabled();
        TempInterfaceState.bt_remove_profile = interf.bt_remove_profile.isDisabled();
        TempInterfaceState.bt_timer_settings = interf.bt_timer_settings.isDisabled();
        TempInterfaceState.bt_stop_presence = interf.bt_stop_presence.isDisabled();
        TempInterfaceState.bt_update_presence = interf.bt_update_presence.isDisabled();
        TempInterfaceState.bt_view_preview_pg1 = interf.bt_view_preview_pg1.isDisabled();
        TempInterfaceState.bt_add_image = interf.bt_add_image.isDisabled();
        TempInterfaceState.bt_remove_image = interf.bt_remove_image.isDisabled();
        TempInterfaceState.bt_remove_all_images = interf.bt_remove_all_images.isDisabled();
        TempInterfaceState.bt_view_preview_pg2 = interf.bt_view_preview_pg2.isDisabled();
        TempInterfaceState.cb_profiles = interf.cb_profiles.isDisabled();
        TempInterfaceState.cb_large_image = interf.cb_large_image.isDisabled();
        TempInterfaceState.cb_small_image = interf.cb_small_image.isDisabled();
        TempInterfaceState.ch_show_timer = interf.ch_show_timer.isDisabled();
        TempInterfaceState.ch_large_img_enabled = interf.ch_large_img_enabled.isDisabled();
        TempInterfaceState.ch_small_img_enabled = interf.ch_small_img_enabled.isDisabled();
        TempInterfaceState.lb_profile = interf.lb_profile.isDisabled();
        TempInterfaceState.lb_details = interf.lb_details.isDisabled();
        TempInterfaceState.lb_state = interf.lb_state.isDisabled();
        TempInterfaceState.lb_group = interf.lb_group.isDisabled();
        TempInterfaceState.lb_group_cur = interf.lb_group_cur.isDisabled();
        TempInterfaceState.lb_group_max = interf.lb_group_max.isDisabled();
        TempInterfaceState.lb_app_id = interf.lb_app_id.isDisabled();
        TempInterfaceState.lb_large_img = interf.lb_large_img.isDisabled();
        TempInterfaceState.lb_small_img = interf.lb_small_img.isDisabled();
        TempInterfaceState.lb_view_preview_pg1 = interf.lb_view_preview_pg1.isDisabled();
        TempInterfaceState.lb_view_preview_pg2 = interf.lb_view_preview_pg2.isDisabled();
        TempInterfaceState.tf_state = interf.tf_state.isDisabled();
        TempInterfaceState.tf_details = interf.tf_details.isDisabled();
        TempInterfaceState.tf_group_cur = interf.tf_group_cur.isDisabled();
        TempInterfaceState.tf_group_max = interf.tf_group_max.isDisabled();
        TempInterfaceState.tf_large_image = interf.tf_large_image.isDisabled();
        TempInterfaceState.tf_small_image = interf.tf_small_image.isDisabled();
        TempInterfaceState.tf_app_id = interf.tf_app_id.isDisabled();
        TempInterfaceState.bt_export_to_jar = interf.bt_export_to_jar.isDisabled();
    }
    
    public static void restore(final Interface interf) {
        interf.bt_add_profile.setDisable(TempInterfaceState.bt_add_profile);
        interf.bt_remove_profile.setDisable(TempInterfaceState.bt_remove_profile);
        interf.bt_timer_settings.setDisable(TempInterfaceState.bt_timer_settings);
        interf.bt_stop_presence.setDisable(TempInterfaceState.bt_stop_presence);
        interf.bt_update_presence.setDisable(TempInterfaceState.bt_update_presence);
        interf.bt_view_preview_pg1.setDisable(TempInterfaceState.bt_view_preview_pg1);
        interf.bt_add_image.setDisable(TempInterfaceState.bt_add_image);
        interf.bt_remove_image.setDisable(TempInterfaceState.bt_remove_image);
        interf.bt_remove_all_images.setDisable(TempInterfaceState.bt_remove_all_images);
        interf.bt_view_preview_pg2.setDisable(TempInterfaceState.bt_view_preview_pg2);
        interf.cb_profiles.setDisable(TempInterfaceState.cb_profiles);
        interf.cb_large_image.setDisable(TempInterfaceState.cb_large_image);
        interf.cb_small_image.setDisable(TempInterfaceState.cb_small_image);
        interf.ch_show_timer.setDisable(TempInterfaceState.ch_show_timer);
        interf.ch_large_img_enabled.setDisable(TempInterfaceState.ch_large_img_enabled);
        interf.ch_small_img_enabled.setDisable(TempInterfaceState.ch_small_img_enabled);
        interf.lb_profile.setDisable(TempInterfaceState.lb_profile);
        interf.lb_details.setDisable(TempInterfaceState.lb_details);
        interf.lb_state.setDisable(TempInterfaceState.lb_state);
        interf.lb_group.setDisable(TempInterfaceState.lb_group);
        interf.lb_group_cur.setDisable(TempInterfaceState.lb_group_cur);
        interf.lb_group_max.setDisable(TempInterfaceState.lb_group_max);
        interf.lb_app_id.setDisable(TempInterfaceState.lb_app_id);
        interf.lb_large_img.setDisable(TempInterfaceState.lb_large_img);
        interf.lb_small_img.setDisable(TempInterfaceState.lb_small_img);
        interf.lb_view_preview_pg1.setDisable(TempInterfaceState.lb_view_preview_pg1);
        interf.lb_view_preview_pg2.setDisable(TempInterfaceState.lb_view_preview_pg2);
        interf.tf_state.setDisable(TempInterfaceState.tf_state);
        interf.tf_details.setDisable(TempInterfaceState.tf_details);
        interf.tf_group_cur.setDisable(TempInterfaceState.tf_group_cur);
        interf.tf_group_max.setDisable(TempInterfaceState.tf_group_max);
        interf.tf_large_image.setDisable(TempInterfaceState.tf_large_image);
        interf.tf_small_image.setDisable(TempInterfaceState.tf_small_image);
        interf.tf_app_id.setDisable(TempInterfaceState.tf_app_id);
        interf.bt_export_to_jar.setDisable(TempInterfaceState.bt_export_to_jar);
    }
    
    public static void disableAll(final Interface interf) {
        interf.bt_add_profile.setDisable(true);
        interf.bt_remove_profile.setDisable(true);
        interf.bt_timer_settings.setDisable(true);
        interf.bt_stop_presence.setDisable(true);
        interf.bt_update_presence.setDisable(true);
        interf.bt_view_preview_pg1.setDisable(true);
        interf.bt_add_image.setDisable(true);
        interf.bt_remove_image.setDisable(true);
        interf.bt_remove_all_images.setDisable(true);
        interf.bt_view_preview_pg2.setDisable(true);
        interf.cb_profiles.setDisable(true);
        interf.cb_large_image.setDisable(true);
        interf.cb_small_image.setDisable(true);
        interf.ch_show_timer.setDisable(true);
        interf.ch_large_img_enabled.setDisable(true);
        interf.ch_small_img_enabled.setDisable(true);
        interf.lb_profile.setDisable(true);
        interf.lb_details.setDisable(true);
        interf.lb_state.setDisable(true);
        interf.lb_group.setDisable(true);
        interf.lb_group_cur.setDisable(true);
        interf.lb_group_max.setDisable(true);
        interf.lb_app_id.setDisable(true);
        interf.lb_large_img.setDisable(true);
        interf.lb_small_img.setDisable(true);
        interf.lb_view_preview_pg1.setDisable(true);
        interf.lb_view_preview_pg2.setDisable(true);
        interf.tf_state.setDisable(true);
        interf.tf_details.setDisable(true);
        interf.tf_group_cur.setDisable(true);
        interf.tf_group_max.setDisable(true);
        interf.tf_large_image.setDisable(true);
        interf.tf_small_image.setDisable(true);
        interf.tf_app_id.setDisable(true);
        interf.bt_export_to_jar.setDisable(true);
    }
}
